/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package org.radarcns.audio;

import org.apache.avro.specific.SpecificData;

@SuppressWarnings("all")
/** Audio data collected by a phone audio input and processed using openSMILE 2.x. */
@org.apache.avro.specific.AvroGenerated
public class OpenSmile2PhoneAudio extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = 5941064442330766761L;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"OpenSmile2PhoneAudio\",\"namespace\":\"org.radarcns.audio\",\"doc\":\"Audio data collected by a phone audio input and processed using openSMILE 2.x.\",\"fields\":[{\"name\":\"time\",\"type\":\"double\",\"doc\":\"device timestamp in UTC (s)\"},{\"name\":\"timeReceived\",\"type\":\"double\",\"doc\":\"device receiver timestamp in UTC (s)\"},{\"name\":\"config\",\"type\":\"string\",\"doc\":\"openSMILE configuration file\"},{\"name\":\"data\",\"type\":\"string\",\"doc\":\"audio features computed by openSMILE recorded in Base64 format\"}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }
  /** device timestamp in UTC (s) */
  @Deprecated public double time;
  /** device receiver timestamp in UTC (s) */
  @Deprecated public double timeReceived;
  /** openSMILE configuration file */
  @Deprecated public java.lang.CharSequence config;
  /** audio features computed by openSMILE recorded in Base64 format */
  @Deprecated public java.lang.CharSequence data;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public OpenSmile2PhoneAudio() {}

  /**
   * All-args constructor.
   * @param time device timestamp in UTC (s)
   * @param timeReceived device receiver timestamp in UTC (s)
   * @param config openSMILE configuration file
   * @param data audio features computed by openSMILE recorded in Base64 format
   */
  public OpenSmile2PhoneAudio(java.lang.Double time, java.lang.Double timeReceived, java.lang.CharSequence config, java.lang.CharSequence data) {
    this.time = time;
    this.timeReceived = timeReceived;
    this.config = config;
    this.data = data;
  }

  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call.
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return time;
    case 1: return timeReceived;
    case 2: return config;
    case 3: return data;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  // Used by DatumReader.  Applications should not call.
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: time = (java.lang.Double)value$; break;
    case 1: timeReceived = (java.lang.Double)value$; break;
    case 2: config = (java.lang.CharSequence)value$; break;
    case 3: data = (java.lang.CharSequence)value$; break;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  /**
   * Gets the value of the 'time' field.
   * @return device timestamp in UTC (s)
   */
  public java.lang.Double getTime() {
    return time;
  }

  /**
   * Sets the value of the 'time' field.
   * device timestamp in UTC (s)
   * @param value the value to set.
   */
  public void setTime(java.lang.Double value) {
    this.time = value;
  }

  /**
   * Gets the value of the 'timeReceived' field.
   * @return device receiver timestamp in UTC (s)
   */
  public java.lang.Double getTimeReceived() {
    return timeReceived;
  }

  /**
   * Sets the value of the 'timeReceived' field.
   * device receiver timestamp in UTC (s)
   * @param value the value to set.
   */
  public void setTimeReceived(java.lang.Double value) {
    this.timeReceived = value;
  }

  /**
   * Gets the value of the 'config' field.
   * @return openSMILE configuration file
   */
  public java.lang.CharSequence getConfig() {
    return config;
  }

  /**
   * Sets the value of the 'config' field.
   * openSMILE configuration file
   * @param value the value to set.
   */
  public void setConfig(java.lang.CharSequence value) {
    this.config = value;
  }

  /**
   * Gets the value of the 'data' field.
   * @return audio features computed by openSMILE recorded in Base64 format
   */
  public java.lang.CharSequence getData() {
    return data;
  }

  /**
   * Sets the value of the 'data' field.
   * audio features computed by openSMILE recorded in Base64 format
   * @param value the value to set.
   */
  public void setData(java.lang.CharSequence value) {
    this.data = value;
  }

  /**
   * Creates a new OpenSmile2PhoneAudio RecordBuilder.
   * @return A new OpenSmile2PhoneAudio RecordBuilder
   */
  public static org.radarcns.audio.OpenSmile2PhoneAudio.Builder newBuilder() {
    return new org.radarcns.audio.OpenSmile2PhoneAudio.Builder();
  }

  /**
   * Creates a new OpenSmile2PhoneAudio RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new OpenSmile2PhoneAudio RecordBuilder
   */
  public static org.radarcns.audio.OpenSmile2PhoneAudio.Builder newBuilder(org.radarcns.audio.OpenSmile2PhoneAudio.Builder other) {
    return new org.radarcns.audio.OpenSmile2PhoneAudio.Builder(other);
  }

  /**
   * Creates a new OpenSmile2PhoneAudio RecordBuilder by copying an existing OpenSmile2PhoneAudio instance.
   * @param other The existing instance to copy.
   * @return A new OpenSmile2PhoneAudio RecordBuilder
   */
  public static org.radarcns.audio.OpenSmile2PhoneAudio.Builder newBuilder(org.radarcns.audio.OpenSmile2PhoneAudio other) {
    return new org.radarcns.audio.OpenSmile2PhoneAudio.Builder(other);
  }

  /**
   * RecordBuilder for OpenSmile2PhoneAudio instances.
   */
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<OpenSmile2PhoneAudio>
    implements org.apache.avro.data.RecordBuilder<OpenSmile2PhoneAudio> {

    /** device timestamp in UTC (s) */
    private double time;
    /** device receiver timestamp in UTC (s) */
    private double timeReceived;
    /** openSMILE configuration file */
    private java.lang.CharSequence config;
    /** audio features computed by openSMILE recorded in Base64 format */
    private java.lang.CharSequence data;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(org.radarcns.audio.OpenSmile2PhoneAudio.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.time)) {
        this.time = data().deepCopy(fields()[0].schema(), other.time);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.timeReceived)) {
        this.timeReceived = data().deepCopy(fields()[1].schema(), other.timeReceived);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.config)) {
        this.config = data().deepCopy(fields()[2].schema(), other.config);
        fieldSetFlags()[2] = true;
      }
      if (isValidValue(fields()[3], other.data)) {
        this.data = data().deepCopy(fields()[3].schema(), other.data);
        fieldSetFlags()[3] = true;
      }
    }

    /**
     * Creates a Builder by copying an existing OpenSmile2PhoneAudio instance
     * @param other The existing instance to copy.
     */
    private Builder(org.radarcns.audio.OpenSmile2PhoneAudio other) {
            super(SCHEMA$);
      if (isValidValue(fields()[0], other.time)) {
        this.time = data().deepCopy(fields()[0].schema(), other.time);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.timeReceived)) {
        this.timeReceived = data().deepCopy(fields()[1].schema(), other.timeReceived);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.config)) {
        this.config = data().deepCopy(fields()[2].schema(), other.config);
        fieldSetFlags()[2] = true;
      }
      if (isValidValue(fields()[3], other.data)) {
        this.data = data().deepCopy(fields()[3].schema(), other.data);
        fieldSetFlags()[3] = true;
      }
    }

    /**
      * Gets the value of the 'time' field.
      * device timestamp in UTC (s)
      * @return The value.
      */
    public java.lang.Double getTime() {
      return time;
    }

    /**
      * Sets the value of the 'time' field.
      * device timestamp in UTC (s)
      * @param value The value of 'time'.
      * @return This builder.
      */
    public org.radarcns.audio.OpenSmile2PhoneAudio.Builder setTime(double value) {
      validate(fields()[0], value);
      this.time = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'time' field has been set.
      * device timestamp in UTC (s)
      * @return True if the 'time' field has been set, false otherwise.
      */
    public boolean hasTime() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'time' field.
      * device timestamp in UTC (s)
      * @return This builder.
      */
    public org.radarcns.audio.OpenSmile2PhoneAudio.Builder clearTime() {
      fieldSetFlags()[0] = false;
      return this;
    }

    /**
      * Gets the value of the 'timeReceived' field.
      * device receiver timestamp in UTC (s)
      * @return The value.
      */
    public java.lang.Double getTimeReceived() {
      return timeReceived;
    }

    /**
      * Sets the value of the 'timeReceived' field.
      * device receiver timestamp in UTC (s)
      * @param value The value of 'timeReceived'.
      * @return This builder.
      */
    public org.radarcns.audio.OpenSmile2PhoneAudio.Builder setTimeReceived(double value) {
      validate(fields()[1], value);
      this.timeReceived = value;
      fieldSetFlags()[1] = true;
      return this;
    }

    /**
      * Checks whether the 'timeReceived' field has been set.
      * device receiver timestamp in UTC (s)
      * @return True if the 'timeReceived' field has been set, false otherwise.
      */
    public boolean hasTimeReceived() {
      return fieldSetFlags()[1];
    }


    /**
      * Clears the value of the 'timeReceived' field.
      * device receiver timestamp in UTC (s)
      * @return This builder.
      */
    public org.radarcns.audio.OpenSmile2PhoneAudio.Builder clearTimeReceived() {
      fieldSetFlags()[1] = false;
      return this;
    }

    /**
      * Gets the value of the 'config' field.
      * openSMILE configuration file
      * @return The value.
      */
    public java.lang.CharSequence getConfig() {
      return config;
    }

    /**
      * Sets the value of the 'config' field.
      * openSMILE configuration file
      * @param value The value of 'config'.
      * @return This builder.
      */
    public org.radarcns.audio.OpenSmile2PhoneAudio.Builder setConfig(java.lang.CharSequence value) {
      validate(fields()[2], value);
      this.config = value;
      fieldSetFlags()[2] = true;
      return this;
    }

    /**
      * Checks whether the 'config' field has been set.
      * openSMILE configuration file
      * @return True if the 'config' field has been set, false otherwise.
      */
    public boolean hasConfig() {
      return fieldSetFlags()[2];
    }


    /**
      * Clears the value of the 'config' field.
      * openSMILE configuration file
      * @return This builder.
      */
    public org.radarcns.audio.OpenSmile2PhoneAudio.Builder clearConfig() {
      config = null;
      fieldSetFlags()[2] = false;
      return this;
    }

    /**
      * Gets the value of the 'data' field.
      * audio features computed by openSMILE recorded in Base64 format
      * @return The value.
      */
    public java.lang.CharSequence getData() {
      return data;
    }

    /**
      * Sets the value of the 'data' field.
      * audio features computed by openSMILE recorded in Base64 format
      * @param value The value of 'data'.
      * @return This builder.
      */
    public org.radarcns.audio.OpenSmile2PhoneAudio.Builder setData(java.lang.CharSequence value) {
      validate(fields()[3], value);
      this.data = value;
      fieldSetFlags()[3] = true;
      return this;
    }

    /**
      * Checks whether the 'data' field has been set.
      * audio features computed by openSMILE recorded in Base64 format
      * @return True if the 'data' field has been set, false otherwise.
      */
    public boolean hasData() {
      return fieldSetFlags()[3];
    }


    /**
      * Clears the value of the 'data' field.
      * audio features computed by openSMILE recorded in Base64 format
      * @return This builder.
      */
    public org.radarcns.audio.OpenSmile2PhoneAudio.Builder clearData() {
      data = null;
      fieldSetFlags()[3] = false;
      return this;
    }

    @Override
    public OpenSmile2PhoneAudio build() {
      try {
        OpenSmile2PhoneAudio record = new OpenSmile2PhoneAudio();
        record.time = fieldSetFlags()[0] ? this.time : (java.lang.Double) defaultValue(fields()[0]);
        record.timeReceived = fieldSetFlags()[1] ? this.timeReceived : (java.lang.Double) defaultValue(fields()[1]);
        record.config = fieldSetFlags()[2] ? this.config : (java.lang.CharSequence) defaultValue(fields()[2]);
        record.data = fieldSetFlags()[3] ? this.data : (java.lang.CharSequence) defaultValue(fields()[3]);
        return record;
      } catch (Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  private static final org.apache.avro.io.DatumWriter
    WRITER$ = new org.apache.avro.specific.SpecificDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  private static final org.apache.avro.io.DatumReader
    READER$ = new org.apache.avro.specific.SpecificDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

}
